// <auto-generated />
using BancoStandard.EmprestimosAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoStandard.EmprestimosAPI.Migrations
{
    [DbContext(typeof(SQLContext))]
    partial class SQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BancoStandard.EmprestimosAPI.Model.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cliente");

                    b.Property<int>("DataAcordo")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("data_acor");

                    b.Property<int>("DataEmp")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("data_emp");

                    b.Property<int>("DataFinal")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("data_final");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("observacao");

                    b.Property<double>("Porcentagem")
                        .HasMaxLength(50)
                        .HasColumnType("float")
                        .HasColumnName("porcentagem");

                    b.Property<string>("TipoPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_pagamento");

                    b.Property<double>("ValorDiv")
                        .HasMaxLength(50)
                        .HasColumnType("float")
                        .HasColumnName("valor_div");

                    b.Property<double>("ValorEmp")
                        .HasMaxLength(50)
                        .HasColumnType("float")
                        .HasColumnName("valor_emp");

                    b.Property<double>("ValorLucro")
                        .HasMaxLength(50)
                        .HasColumnType("float")
                        .HasColumnName("valor_luc");

                    b.HasKey("Id");

                    b.ToTable("contract");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cliente = "Napoleão Bonaparte",
                            DataAcordo = 0,
                            DataEmp = 0,
                            DataFinal = 0,
                            Observacao = "Pagamento em dia",
                            Porcentagem = 0.0,
                            TipoPagamento = "Ramo Diário",
                            ValorDiv = 1300.0,
                            ValorEmp = 1000.0,
                            ValorLucro = 300.0
                        },
                        new
                        {
                            Id = 2L,
                            Cliente = "Costa Lucas",
                            DataAcordo = 0,
                            DataEmp = 0,
                            DataFinal = 0,
                            Observacao = "Pagamento em dia",
                            Porcentagem = 0.0,
                            TipoPagamento = "Pagamento Mensal",
                            ValorDiv = 6500.0,
                            ValorEmp = 5000.0,
                            ValorLucro = 1500.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
