// <auto-generated />
using System;
using BancoStandard.EmprestimosAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoStandard.EmprestimosAPI.Migrations
{
    [DbContext(typeof(SQLContext))]
    partial class SQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BancoStandard.EmprestimosAPI.Model.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cliente");

                    b.Property<DateTime>("DataAcordo")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("data_acor");

                    b.Property<DateTime>("DataEmp")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("data_emp");

                    b.Property<DateTime>("DataFinal")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("data_final");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("observacao");

                    b.Property<double>("Porcentagem")
                        .HasMaxLength(50)
                        .HasColumnType("float")
                        .HasColumnName("porcentagem");

                    b.Property<string>("TipoPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_pagamento");

                    b.Property<double>("ValorDiv")
                        .HasMaxLength(50)
                        .HasColumnType("float")
                        .HasColumnName("valor_div");

                    b.Property<double>("ValorEmp")
                        .HasMaxLength(50)
                        .HasColumnType("float")
                        .HasColumnName("valor_emp");

                    b.Property<double>("ValorLucro")
                        .HasMaxLength(50)
                        .HasColumnType("float")
                        .HasColumnName("valor_luc");

                    b.HasKey("Id");

                    b.ToTable("contract");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cliente = "Napoleão Bonaparte",
                            DataAcordo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEmp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFinal = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Observacao = "Pagamento em dia",
                            Porcentagem = 30.0,
                            TipoPagamento = "Ramo Diário",
                            ValorDiv = 1300.0,
                            ValorEmp = 1000.0,
                            ValorLucro = 300.0
                        },
                        new
                        {
                            Id = 2L,
                            Cliente = "Costa Lucas",
                            DataAcordo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEmp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFinal = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Observacao = "Pagamento em dia",
                            Porcentagem = 30.0,
                            TipoPagamento = "Pagamento Mensal",
                            ValorDiv = 6500.0,
                            ValorEmp = 5000.0,
                            ValorLucro = 1500.0
                        },
                        new
                        {
                            Id = 3L,
                            Cliente = "James de Paris",
                            DataAcordo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEmp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFinal = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Observacao = "Pagamento em dia",
                            Porcentagem = 30.0,
                            TipoPagamento = "Pagamento Mensal",
                            ValorDiv = 6500.0,
                            ValorEmp = 5000.0,
                            ValorLucro = 1500.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
